apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: acme-peer0
  namespace: acme
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: acme-peer0
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/peernode    
  values:
    metadata:
      namespace: acme
      images:
        couchdb: couchdb:3.1
        peer: hyperledger/fabric-peer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        
    peer:
      name: peer0
      gossippeeraddress: peer0.acme:7051
      gossipexternalendpoint: peer0.acme.bank.com:8443
      localmspid: acmeMSP
      loglevel: info
      tlsstatus: true
      builder: hyperledger/fabric-ccenv:2.2.2
      couchdb:
        username: acme-user

    storage:
      peer:
        storageclassname: acmesc
        storagesize: 512Mi
      couchdb:
        storageclassname: acmesc
        storagesize: 1Gi

    vault:
      role: vault-role
      address: http://35.175.171.11:8200
      authpath: localacme-auth
      secretprefix: secretsv2/data/crypto/peerOrganizations/acme/peers/peer0.acme
      secretambassador: secretsv2/data/crypto/peerOrganizations/acme/ambassador
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretcouchdbpass: secretsv2/data/credentials/acme/couchdb/acme?user

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7051
        events:
          clusteripport: 7053
        couchdb:
          clusteripport: 5984
          
    proxy:
      provider: "haproxy"
      external_url_suffix: bank.com

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
